#!/usr/bin/bash

CAPS_STATUS=$(xset -q | grep Caps | awk '{ print $4 }')

#CAPS off
if [[ ${CAPS_STATUS} = "off" ]]; then
    COLOR="#888888"
    CAPS_SHOW="caps"

# CAPS on
else
    COLOR="#C3BEBD"
    CAPS_SHOW="CAPS"
fi

echo "<span color='$COLOR'>$CAPS_SHOW</span>"