#!/bin/bash

#cmus
#ARTIST=$(cmus-remote -Q | grep ' artist ' | cut -d ' ' -f3-)
#TITLE=$(cmus-remote -Q | grep title | cut -d ' ' -f2-)

#clementine
ARTIST=$(qdbus org.mpris.MediaPlayer2.clementine /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get org.mpris.MediaPlayer2.Player Metadata | grep artist | cut -d ' ' -f2-)
TITLE=$(qdbus org.mpris.MediaPlayer2.clementine /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get org.mpris.MediaPlayer2.Player Metadata | grep title  | cut -d ' ' -f2-)

if [[ $ARTIST != "" ]]; then
  OUTPUT=$ARTIST
fi

if [[ $TITLE != "" ]]; then
  OUTPUT="$OUTPUT - $TITLE"
fi

echo "<span color='#C3BEBD'>"$OUTPUT"</span>"