#!/bin/bash

#()

DATE=$(date +'%A %d %b %Y')

# get current month
MONTH=$(date +'%m')

# between March and May 
if [[ $MONTH -ge 3 && $MONTH -le 5 ]]; then
  IMAGE=""
  COLOR="#BDE077" #lime color ^__^

# between June and August
elif [[ $MONTH -ge 6 && $MONTH -le 8 ]]; then
  IMAGE=""
  COLOR="#FFC178"

# between September and November 
elif [[ $MONTH -ge 9 && $MONTH -le 11 ]]; then
  IMAGE=""
  COLOR="#ffffdd"

# between December and February
else
  IMAGE=""
  COLOR="#899aab"
fi

COLOR="#888888"
echo "<span color='$COLOR'>$IMAGE</span> <span color='#C3BEBD'>$DATE</span>"

