#!/bin/bash
#    

STEP=$BLOCK_INSTANCE

case $BLOCK_BUTTON in
  3) amixer -q set Master toggle ;;  # right click, mute/unmute
  4) amixer -q set Master ${STEP}+ unmute ;; # scroll up, increase
  5) amixer -q set Master ${STEP}- unmute ;; # scroll down, decrease
esac

VALUE=$(awk -F"[][]" '/Front Left:/ { sub(/%/,""); print $2 }' <(amixer sget Master))
MUTE=$(awk -F"[][]" '/Front Left:/ { sub(/%/,""); print $4 }' <(amixer sget Master))
IMAGE=""

# mute
#if [[ $MUTE = "off" || $VALUE = "0%" ]]; then
COLOR1="#888888"
COLOR2="#C3BEBD"
if [[ $VALUE = "0" ]]; then
  IMAGE=""
  COLOR2="#7D6F67"
# not mute
fi

echo "<span color='$COLOR1'>$IMAGE</span> <span color='$COLOR2'>$VALUE%</span>"